### ISSUE TITLE
[1차/QA][글쓰기페이지/감정분석] 상호작용 태그의 ‘자아비판’이 테마 태그 데이터로 내려와지는 현상

### ISSUE THREAD

**Issue by firstquarterlee** [git-in-official/front#48]
## 테스트환경 및 시뮬레이션 경로

1. 테스트기기:  iOS
2. 시뮬레이션 경로:
- [ ] 구글로 로그인 한후 , '원형 글감 선택 메뉴바'를 클릭한다
- [ ] '원형 글감 선택 메뉴바'에서 글감 선택 후 '나는 바보다'라고 글을 작성한다. 
<img width="316" alt="스크린샷 2024-09-01 오후 10 31 34" src="https://github.com/user-attachments/assets/0e0d2d91-8152-4759-b568-bdaa3d614601">
- [ ] 글 작성 완료 후  '원형 글감 선택 메뉴바'를 누르고, '감정 분석하기' 버튼을 클릭한다.
- [ ] 확인 버튼 누른 후, 글쓰기 페이지(감정분석)로 이동한다.

## 문제현상
- '테마' 태그에 '상호작용' 태그인 '자아비판'이 노출되고 있음

## 기대사항
- '상호작용' 태그에만 '자아비판' 태그가 내려져야함

## 참고할만한 자료(선택)

**Comment by junefiv** [comment]
<img width="248" alt="스크린샷 2024-09-01 224439" src="https://github.com/user-attachments/assets/1f0a7bb3-fb29-495e-9034-35b86e36a16a">

태그구분입니다.
