### ISSUE TITLE
[1차/QA][메인페이지/글읽기화면] 페이지 최초 진입시 ’글감을 선택하여 집필해보세요’ 말풍선 노출 되어야함

### ISSUE THREAD

**Issue by firstquarterlee** [git-in-official/front#49]
## 테스트환경 및 시뮬레이션 경로
1. 테스트기기:  iOS
2. 시뮬레이션 경로:
- [ ] 구글로 로그인 한후 , '메인페이지/글읽기'로 진입한다.

## 문제현상
- 페이지 최초 진입시 ’글감을 선택하여 집필해보세요’ 말풍선 노출 안되고 있음

## 기대사항
- ’글감을 선택하여 집필해보세요’ 말풍선 노출 되어야함
<img width="233" alt="스크린샷 2024-09-01 오후 10 40 18" src="https://github.com/user-attachments/assets/bc9995a8-3b45-4f21-a908-2e05ba98e654">

## 참고할만한 자료(선택)

**Comment by junefiv** [comment]
가능하면 페이지를 3번 넘길때마다 말풍선이 나오면 사용자경험이 올라갈 것 같습니다.

**Comment by hennie-yun** [comment]
페이지를 3번 넘길때마다 말풍선이 나오게 말풍선 추가
