### ISSUE TITLE
[1차/QA][글쓰기페이지/집필화면] 글쓰기 페이지에서 폰트 선택시 KoPubBatangPro 폰트도 선택 가능해야됨

### ISSUE THREAD

**Issue by firstquarterlee** [git-in-official/front#50]
## 테스트환경 및 시뮬레이션 경로
1. 테스트기기:  iOS
2. 시뮬레이션 경로:
- [ ] 구글로 로그인 한후, '원형 글감 선택 메뉴바'를 클릭한다
- [ ] '원형 글감 선택 메뉴바'에서 글감 선택 후 글쓰기페이지/집필화면으로 이동한다

## 문제현상
- 현재 Noto Sans 시리즈 폰트만 선택 가능함

## 기대사항
- 글쓰기 페이지에서 폰트 선택시 KoPubBatangPro 폰트도 선택 가능해야됨
<img width="324" alt="스크린샷 2024-09-01 오후 10 56 46" src="https://github.com/user-attachments/assets/1fea0d09-c847-4c35-b6c4-6d7356a90edf">

## 참고할만한 자료(선택)

**Comment by junefiv** [comment]
노토산스만 선택 가능한 것이 아니라
폰트사이즈와 얼라인은 변경한대로 글읽기 페이지에 적용이 되는데
폰트종류는 변경을 하더라도 적용이 안 되는 문제가 있습니다.
