### ISSUE TITLE
[1차/QA][공통] KoPubBatangPro 공통 폰트 적용 작업

### ISSUE THREAD

**Issue by firstquarterlee** [git-in-official/front#54]
## 테스트환경 및 시뮬레이션 경로
1. 테스트기기:  iOS
2. 시뮬레이션 경로:

## 문제현상
- 공통 폰트가 Noto Sans로 적용되어 있음

## 기대사항
- KoPubBatangPro 공통 폰트 적용 되어야 함

## 참고할만한 자료(선택)

**Comment by junefiv** [comment]
현재 모달창과 일부 페이지는 폰트가 노토산스입니다. 위 설명처럼 피그마에 사용한 코펍바탕으로 변경해주세요.

단, 유저가 글을 쓸 때 폰트를 변경해서 탈고한 경우엔 유저가 선택한 폰트가 프린트 되야합니다. 지금 얼라인과 폰트사이즈처럼요
