### ISSUE TITLE
[1차/QA][글쓰기페이지/감정분석] 감정태그 수정 후 되돌아가기 버튼 클릭시 '현재 기분 선택' 페이지로 이동되는 현상

### ISSUE THREAD

**Issue by firstquarterlee** [git-in-official/front#56]
## 테스트환경 및 시뮬레이션 경로
- 테스트기기:  iOS
- 시뮬레이션 경로:
- [ ] 구글로 로그인 한후 , '원형 글감 선택 메뉴바'를 클릭한다
- [ ] '원형 글감 선택 메뉴바'에서 글감 선택 후 글을 작성한다.
- [ ] 글 작성 완료 후  '원형 글감 선택 메뉴바'를 누르고, '감정 분석하기' 버튼을 클릭한다.
- [ ] 확인 버튼 누른 후, 글쓰기 페이지(감정분석)로 이동한다.
- [ ] 상호작용 태그 중 한개를 클릭 후, 변경할 감정태그를 선택한다.
- [ ] '변경' 버튼을 누른후, 변경된 감정태그를 확인하고 '닫기' 버튼을 누른다.

## 문제현상
- 감정 태그 변경 후 '닫기' 버튼 누르면 시는 잘 변경이 되어 업데이트 되는데,
자동으로 '현재 기분 선택' 페이지로 이동되는 현상 발생함
- 이후 감정 클릭후 입력 완료 버튼을 누르면 아래와 같이 에러 발생됨 
<img width="462" alt="스크린샷 2024-09-02 오전 2 10 37" src="https://github.com/user-attachments/assets/90f02bec-23fd-4626-a942-c29e737a93e7">

## 기대사항
- '닫기' 버튼 클릭하면 '현재 기분 선택' 페이지로 자동 라우팅 되지 말아야 됨

## 참고할만한 자료(선택)

**Comment by hennie-yun** [comment]
모달창 띄어서 변경 한번만 누르게 변경
